### PR TITLE
add support for dark mode on ios and add support for iphone x form factor

### LINKED ISSUE #12: add dark theme
iQuassel should use the current native theme, weather it is dark or light. Colors of text and nick highlights should be based on this as well.

### PR DESCRIPTION
**Pull request by lowlyw**
fixes https://github.com/woboq/iquassel/issues/12

this is really just support on ios13, maybe we can update the minimum sdk version too?

### CODE REVIEW

**Comment by lowlyw** [comment]
this also fixes https://github.com/woboq/iquassel/issues/7

**Comment by guruz** [comment]
awesome, thanks for contributing

**Comment by guruz** [comment]
Works on my iPhone11: 

IMG_4204

**Review by guruz — APPROVED** [review]

**Comment by guruz** [comment]
@lowlyw I stashed some things (and re-ordered): https://github.com/woboq/iquassel/commits/master
Hope I didn't mess anything up though..

**Comment by guruz** [comment]
> this is really just support on ios13, maybe we can update the minimum sdk version too?

4cd237ab02cafbaffac6b39b5b16ee24ca7b4092 ?

**Pull request merged**
